name: "Upload Coverage to Codecov"
description: "Uploads code coverage reports to Codecov with graceful failure handling"

branding:
  icon: "bar-chart-2"
  color: "red"

inputs:
  codecov-token:
    description: "Codecov token for uploading coverage reports"
    required: false
  files:
    description: "Comma-separated list of coverage files to upload"
    required: true
  flags:
    description: "Flag to identify coverage type (e.g., frontend, backend)"
    required: false
    default: ""
  name:
    description: "Custom name for the upload"
    required: false
    default: ""
  slug:
    description: "Repository slug (owner/repo)"
    required: false
    default: ""
  fail-ci-if-error:
    description: "Fail CI if Codecov upload fails"
    required: false
    default: "false"
  verbose:
    description: "Enable verbose output for debugging"
    required: false
    default: "false"
  fail-on-upload-error:
    description: "Fail the workflow if Codecov upload fails"
    required: false
    default: "false"

outputs:
  upload-failed:
    description: "Whether the Codecov upload failed"
    value: ${{ steps.status.outputs.upload-failed }}

runs:
  using: "composite"
  steps:
    - name: Upload coverage to Codecov
      id: codecov
      if: inputs.codecov-token != ''
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
      continue-on-error: true
      with:
        files: ${{ inputs.files }}
        flags: ${{ inputs.flags }}
        name: ${{ inputs.name }}
        slug: ${{ inputs.slug }}
        fail_ci_if_error: ${{ inputs.fail-ci-if-error }}
        verbose: ${{ inputs.verbose }}
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}

    - name: Set upload status
      id: status
      shell: bash
      run: |
        if [ "${{ steps.codecov.outcome }}" == "failure" ]; then
          echo "upload-failed=true" >> $GITHUB_OUTPUT
          echo "⚠️ Codecov upload failed — continuing pipeline"
        else
          echo "upload-failed=false" >> $GITHUB_OUTPUT
          echo "✅ Codecov upload succeeded"
        fi

    - name: Fail on upload error
      if: inputs.fail-on-upload-error == 'true' && steps.status.outputs.upload-failed == 'true'
      shell: bash
      run: |
        echo "❌ Codecov upload failed and fail-on-upload-error is enabled"
        exit 1
